### ISSUE TITLE
Incompatible mods. Can u fix it?

### ISSUE THREAD

**Issue by 18cerf** [anviaan/InventoryTweak#6]
### What happened?

# Incompatible mods

I don't know what this means, but can you fix it?

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'oωo-sentinel' (owo-sentinel) 0.12.10+1.21 with mod 'oωo-sentinel' (owo-sentinel), version 0.12.15 or later.
More details:
	 - Mod 'Inventory Tweak' (inventorytweak) 3.0 requires version 0.12.15 or later of mod 'oωo-sentinel' (owo-sentinel), but only the wrong version is present: 0.12.10+1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Mod Version

InventoryTweaks-3.0

### Minecraft Version

1.21

### Relevant log output

```Shell
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'oωo-sentinel' (owo-sentinel) 0.12.10+1.21 with mod 'oωo-sentinel' (owo-sentinel), version 0.12.15 or later.
More details:
	 - Mod 'Inventory Tweak' (inventorytweak) 3.0 requires version 0.12.15 or later of mod 'oωo-sentinel' (owo-sentinel), but only the wrong version is present: 0.12.10+1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Florke64** [comment]
You have another mod `oωo` installed. You need to update it to version 0.12.15 or later. Currently you're on 0.12.10.
